{% set name = "learn-python-ceg-test" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/learn_python_ceg_test-{{ version }}.tar.gz
  sha256: 3321fac11b921d46a11d13ab38a6137b9c929b8c838dfdc19b97746715db412e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas

test:
  imports:
    - learn_python_ceg_test
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mike-mendoza/learn_python_ceg_test
  summary: learn_python check answers
  license: GPL-3.0-Only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mike-mendoza
